version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    docker:
      - image: cimg/node:18.9.1
    auth:
      username: $DOCKERHUB_USERNAME
      password: $DOCKERHUB_PASSWORD
    steps:
      - node/install
      - checkout
      - run:
          name: Print node version
          command: |
            node --version
      - run:
          name: Print Docker version
          command: |
            docker --version
      - run:
          name: Build docker Image
          command: |
            docker build -t simple-node .
      - run:
          name: Tag Image with Hub
          command: |
            docker tag simple-node $DOCKERHUB_USERNAME/simple-node:latest
      - run:
          name: Push Image to Hub
          command: |
            docker push $DOCKERHUB_USERNAME/simple-node
